% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
]{article}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={DMAW\_MIDTERMS\_KHAFAJI},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{DMAW\_MIDTERMS\_KHAFAJI}
\author{}
\date{\vspace{-2.5em}}

\begin{document}
\maketitle

\section{Exploring Customer Churn}\label{exploring-customer-churn}

Our data set involves data relevant to customer churn. It has the
following columns:

\begin{itemize}
\tightlist
\item
  CustomerID: The customer's ID
\item
  Gender: the customer's gender
\item
  SeniorCitizen: if the customer is a senior citizen
\item
  Partner: If the customer is a partner
\item
  Dependents: if the customer has dependents
\item
  Tenure: The tenure of the customer
\item
  PhoneService: If the customer has phone service
\item
  InternetService: The internet service of the customer, if they have
  one
\item
  Contract: Their contract type
\item
  MonthlyCharges: Their monthly charge for the service
\item
  TotalCharges: Total charged amount
\item
  Churn: If customer left the service or not.
\end{itemize}

\subsection{Data Mining}\label{data-mining}

\subsubsection{loading data}\label{loading-data}

First, let's load our data set into a variable called cust\_churn

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cust\_churn }\OtherTok{\textless{}{-}} \FunctionTok{read\_csv}\NormalTok{(}\StringTok{"customer\_churn.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Rows: 10000 Columns: 12
## -- Column specification --------------------------------------------------------
## Delimiter: ","
## chr (8): CustomerID, Gender, Partner, Dependents, PhoneService, InternetServ...
## dbl (4): SeniorCitizen, Tenure, MonthlyCharges, TotalCharges
## 
## i Use `spec()` to retrieve the full column specification for this data.
## i Specify the column types or set `show_col_types = FALSE` to quiet this message.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{head}\NormalTok{(cust\_churn)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 12
##   CustomerID Gender SeniorCitizen Partner Dependents Tenure PhoneService
##   <chr>      <chr>          <dbl> <chr>   <chr>       <dbl> <chr>       
## 1 CUST00001  Male               0 No      No             65 Yes         
## 2 CUST00002  Male               0 No      No             26 Yes         
## 3 CUST00003  Male               0 Yes     No             54 Yes         
## 4 CUST00004  Female             0 Yes     Yes            70 Yes         
## 5 CUST00005  Male               0 No      No             53 Yes         
## 6 CUST00006  Female             0 No      Yes            45 Yes         
## # i 5 more variables: InternetService <chr>, Contract <chr>,
## #   MonthlyCharges <dbl>, TotalCharges <dbl>, Churn <chr>
\end{verbatim}

now, let's get the summary of the dataset:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"The structure of the data set is:}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## The structure of the data set is:
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\FunctionTok{str}\NormalTok{(cust\_churn))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## spc_tbl_ [10,000 x 12] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
##  $ CustomerID     : chr [1:10000] "CUST00001" "CUST00002" "CUST00003" "CUST00004" ...
##  $ Gender         : chr [1:10000] "Male" "Male" "Male" "Female" ...
##  $ SeniorCitizen  : num [1:10000] 0 0 0 0 0 0 0 0 0 0 ...
##  $ Partner        : chr [1:10000] "No" "No" "Yes" "Yes" ...
##  $ Dependents     : chr [1:10000] "No" "No" "No" "Yes" ...
##  $ Tenure         : num [1:10000] 65 26 54 70 53 45 35 20 48 33 ...
##  $ PhoneService   : chr [1:10000] "Yes" "Yes" "Yes" "Yes" ...
##  $ InternetService: chr [1:10000] "Fiber optic" "Fiber optic" "Fiber optic" "DSL" ...
##  $ Contract       : chr [1:10000] "Month-to-month" "Month-to-month" "Month-to-month" "One year" ...
##  $ MonthlyCharges : num [1:10000] 20 65.1 49.4 31.2 103.9 ...
##  $ TotalCharges   : num [1:10000] 1303 1694 2667 2183 5505 ...
##  $ Churn          : chr [1:10000] "No" "No" "No" "No" ...
##  - attr(*, "spec")=
##   .. cols(
##   ..   CustomerID = col_character(),
##   ..   Gender = col_character(),
##   ..   SeniorCitizen = col_double(),
##   ..   Partner = col_character(),
##   ..   Dependents = col_character(),
##   ..   Tenure = col_double(),
##   ..   PhoneService = col_character(),
##   ..   InternetService = col_character(),
##   ..   Contract = col_character(),
##   ..   MonthlyCharges = col_double(),
##   ..   TotalCharges = col_double(),
##   ..   Churn = col_character()
##   .. )
##  - attr(*, "problems")=<externalptr> 
## NULL
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#cat("The summary of the data set is:\textbackslash{}n")}
\CommentTok{\#summary(cust\_churn)}

\FunctionTok{cat}\NormalTok{(}\StringTok{"}\SpecialCharTok{\textbackslash{}n\textbackslash{}n}\StringTok{The Summary Statistics for the data set are:}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## 
## The Summary Statistics for the data set are:
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{skimr}\SpecialCharTok{::}\FunctionTok{skim}\NormalTok{(cust\_churn)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}ll@{}}
\caption{Data summary}\tabularnewline
\toprule\noalign{}
\endfirsthead
\endhead
\bottomrule\noalign{}
\endlastfoot
Name & cust\_churn \\
Number of rows & 10000 \\
Number of columns & 12 \\
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ & \\
Column type frequency: & \\
character & 8 \\
numeric & 4 \\
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ & \\
Group variables & None \\
\end{longtable}

\textbf{Variable type: character}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.2162}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1351}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1892}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.0541}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.0541}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.0811}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1216}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1486}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
skim\_variable
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
n\_missing
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
complete\_rate
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
min
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
max
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
empty
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
n\_unique
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
whitespace
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
CustomerID & 0 & 1 & 9 & 9 & 0 & 10000 & 0 \\
Gender & 0 & 1 & 4 & 6 & 0 & 2 & 0 \\
Partner & 0 & 1 & 2 & 3 & 0 & 2 & 0 \\
Dependents & 0 & 1 & 2 & 3 & 0 & 2 & 0 \\
PhoneService & 0 & 1 & 2 & 3 & 0 & 2 & 0 \\
InternetService & 0 & 1 & 2 & 11 & 0 & 3 & 0 \\
Contract & 0 & 1 & 8 & 14 & 0 & 3 & 0 \\
Churn & 0 & 1 & 2 & 3 & 0 & 2 & 0 \\
\end{longtable}

\textbf{Variable type: numeric}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.1531}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.1020}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.1429}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.0816}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.0816}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.0612}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.0714}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.0816}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.0816}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.0816}}
  >{\raggedright\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.0612}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
skim\_variable
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
n\_missing
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
complete\_rate
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
mean
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
sd
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
p0
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
p25
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
p50
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
p75
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
p100
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
hist
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
SeniorCitizen & 0 & 1 & 0.15 & 0.36 & 0.00 & 0.00 & 0.00 & 0.00 & 1.00 &
▇▁▁▁▂ \\
Tenure & 0 & 1 & 35.22 & 20.79 & 0.00 & 17.00 & 35.00 & 53.00 & 71.00 &
▇▇▇▇▇ \\
MonthlyCharges & 0 & 1 & 70.18 & 29.03 & 20.02 & 44.88 & 70.56 & 95.77 &
119.99 & ▇▇▇▇▇ \\
TotalCharges & 0 & 1 & 2455.81 & 1854.59 & 0.00 & 961.21 & 2025.58 &
3610.98 & 8425.57 & ▇▆▃▂▁ \\
\end{longtable}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"}\SpecialCharTok{\textbackslash{}n\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

We can see from our summary that we have 1 ID table, 7 categorical
variables, and three numerical variables. We also have no missing
values.

\subsubsection{Data Visualization}\label{data-visualization}

Let's take a quick look at what our data says.

Let's take a look at monthly charges per gender.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cust\_churn }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{Gender, }\AttributeTok{y=}\NormalTok{MonthlyCharges)) }\SpecialCharTok{+}
  \FunctionTok{geom\_boxplot}\NormalTok{()}\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title=}\StringTok{"Distribution of Monthly Charges for each gender"}\NormalTok{, }\AttributeTok{y=}\StringTok{"Monthly Charges"}\NormalTok{, }\AttributeTok{x=} \StringTok{"Gender"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{DMAW_MIDTERMS_KHAFAJI_files/figure-latex/Monthly charges vs Gender-1.pdf}}

We can see that the median monthly charges for each gender is roughly
equal, if not slightly less for female customers. However, the
interquartile range of the monthly charges for females is slightly
larger than for their male counterparts.

Next, let's look at the distribution of monthly charges for each churn
category.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cust\_churn }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{Churn, }\AttributeTok{y=}\NormalTok{MonthlyCharges)) }\SpecialCharTok{+}
  \FunctionTok{geom\_boxplot}\NormalTok{()}\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title=}\StringTok{"Distribution of Monthly Charges for each Churn Category"}\NormalTok{, }\AttributeTok{y=}\StringTok{"Monthly Charges"}\NormalTok{, }\AttributeTok{x=} \StringTok{"Churn"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{DMAW_MIDTERMS_KHAFAJI_files/figure-latex/monthly charges vs senior citizen-1.pdf}}

We can see that the median monthly charges for churned customer is
slightly less than current customers. This also follows for the 1st and
3rd quartile.

Lastly, let's look at monthly charges for vs tenure, faceted by gender.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cust\_churn }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{Tenure, }\AttributeTok{y=}\NormalTok{MonthlyCharges)) }\SpecialCharTok{+}
  \FunctionTok{geom\_density2d\_filled}\NormalTok{()}\SpecialCharTok{+}
  \FunctionTok{facet\_wrap}\NormalTok{(}\SpecialCharTok{\textasciitilde{}}\NormalTok{Gender)}\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title=}\StringTok{"Monthly Charges Tenure"}\NormalTok{, }\AttributeTok{y=}\StringTok{"Monthly Charges"}\NormalTok{, }\AttributeTok{x=} \StringTok{"Tenure"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{DMAW_MIDTERMS_KHAFAJI_files/figure-latex/monthly charges vs tenure by gender-1.pdf}}

The 2d Density plot shows us that, while the distribution isn't really
uniform, The monthly charges for female customers rises with their
tenure. In contrast, for males, their monthly charge is relatively
higher for customers that has short tenures, lower for customers with
medium or long length of tenures.

\subsubsection{Data Transformation}\label{data-transformation}

Now, since we don't have missing values, all we have to do is convert
categorical variables to factor variables. We would also normalize or
standardize numerical features, if necessary.

let's first convert our categorical variables to factor variables:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cust\_churn }\OtherTok{\textless{}{-}}\NormalTok{ cust\_churn }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{mutate}\NormalTok{( }\AttributeTok{SeniorCitizen =} \FunctionTok{case\_when}\NormalTok{(}
\NormalTok{                                                               SeniorCitizen }\SpecialCharTok{==} \DecValTok{0} \SpecialCharTok{\textasciitilde{}} \StringTok{"Not Senior"}\NormalTok{,}
\NormalTok{                                                               SeniorCitizen }\SpecialCharTok{==} \DecValTok{1} \SpecialCharTok{\textasciitilde{}} \StringTok{"Senior Citizen"}
\NormalTok{                                                               )) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate\_at}\NormalTok{( }\FunctionTok{c}\NormalTok{(}\StringTok{\textquotesingle{}Gender\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}SeniorCitizen\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}Partner\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}Dependents\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}PhoneService\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}InternetService\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}Contract\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}Churn\textquotesingle{}}\NormalTok{), as.factor)}

\FunctionTok{str}\NormalTok{(cust\_churn)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## tibble [10,000 x 12] (S3: tbl_df/tbl/data.frame)
##  $ CustomerID     : chr [1:10000] "CUST00001" "CUST00002" "CUST00003" "CUST00004" ...
##  $ Gender         : Factor w/ 2 levels "Female","Male": 2 2 2 1 2 1 1 1 1 1 ...
##  $ SeniorCitizen  : Factor w/ 2 levels "Not Senior","Senior Citizen": 1 1 1 1 1 1 1 1 1 1 ...
##  $ Partner        : Factor w/ 2 levels "No","Yes": 1 1 2 2 1 1 2 2 2 1 ...
##  $ Dependents     : Factor w/ 2 levels "No","Yes": 1 1 1 2 1 2 1 2 2 1 ...
##  $ Tenure         : num [1:10000] 65 26 54 70 53 45 35 20 48 33 ...
##  $ PhoneService   : Factor w/ 2 levels "No","Yes": 2 2 2 2 2 2 2 2 1 2 ...
##  $ InternetService: Factor w/ 3 levels "DSL","Fiber optic",..: 2 2 2 1 1 2 3 2 3 3 ...
##  $ Contract       : Factor w/ 3 levels "Month-to-month",..: 1 1 1 2 1 1 2 1 1 3 ...
##  $ MonthlyCharges : num [1:10000] 20 65.1 49.4 31.2 103.9 ...
##  $ TotalCharges   : num [1:10000] 1303 1694 2667 2183 5505 ...
##  $ Churn          : Factor w/ 2 levels "No","Yes": 1 1 1 1 2 2 2 2 1 1 ...
\end{verbatim}

Now, let's normalize our numeric data:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cust\_churn\_norm }\OtherTok{\textless{}{-}}\NormalTok{ cust\_churn }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{mutate}\NormalTok{(}\FunctionTok{across}\NormalTok{(}\FunctionTok{where}\NormalTok{(is.numeric), }\SpecialCharTok{\textasciitilde{}} \FunctionTok{as.numeric}\NormalTok{(}\FunctionTok{scale}\NormalTok{(.x))))}

\FunctionTok{head}\NormalTok{(cust\_churn\_norm)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 12
##   CustomerID Gender SeniorCitizen Partner Dependents Tenure PhoneService
##   <chr>      <fct>  <fct>         <fct>   <fct>       <dbl> <fct>       
## 1 CUST00001  Male   Not Senior    No      No          1.43  Yes         
## 2 CUST00002  Male   Not Senior    No      No         -0.444 Yes         
## 3 CUST00003  Male   Not Senior    Yes     No          0.903 Yes         
## 4 CUST00004  Female Not Senior    Yes     Yes         1.67  Yes         
## 5 CUST00005  Male   Not Senior    No      No          0.855 Yes         
## 6 CUST00006  Female Not Senior    No      Yes         0.470 Yes         
## # i 5 more variables: InternetService <fct>, Contract <fct>,
## #   MonthlyCharges <dbl>, TotalCharges <dbl>, Churn <fct>
\end{verbatim}

As we can see, our numeric data is now z-score normalized.

\subsubsection{Data Wrangling}\label{data-wrangling}

Since we have a relatively huge data set, let's filter outliers, if our
data has them. Since we have normalized our numerical data, we can
simply filter if the absolute value of their z-score is greater than 3.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cust\_churn\_norm }\OtherTok{\textless{}{-}}\NormalTok{ cust\_churn\_norm }\SpecialCharTok{\%\textgreater{}\%} 
\NormalTok{  dplyr}\SpecialCharTok{::}\FunctionTok{filter}\NormalTok{(}\FunctionTok{across}\NormalTok{(is.numeric, }\SpecialCharTok{\textasciitilde{}} \FunctionTok{abs}\NormalTok{(.x) }\SpecialCharTok{\textless{}} \DecValTok{3}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: Using `across()` in `filter()` was deprecated in dplyr 1.0.8.
## i Please use `if_any()` or `if_all()` instead.
## Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
## generated.
\end{verbatim}

\begin{verbatim}
## Warning: There was 1 warning in `dplyr::filter()`.
## i In argument: `across(is.numeric, ~abs(.x) < 3)`.
## Caused by warning:
## ! Use of bare predicate functions was deprecated in tidyselect 1.1.0.
## i Please use wrap predicates in `where()` instead.
##   # Was:
##   data %>% select(is.numeric)
## 
##   # Now:
##   data %>% select(where(is.numeric))
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cust\_churn\_norm}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 9,972 x 12
##    CustomerID Gender SeniorCitizen Partner Dependents  Tenure PhoneService
##    <chr>      <fct>  <fct>         <fct>   <fct>        <dbl> <fct>       
##  1 CUST00001  Male   Not Senior    No      No          1.43   Yes         
##  2 CUST00002  Male   Not Senior    No      No         -0.444  Yes         
##  3 CUST00003  Male   Not Senior    Yes     No          0.903  Yes         
##  4 CUST00004  Female Not Senior    Yes     Yes         1.67   Yes         
##  5 CUST00005  Male   Not Senior    No      No          0.855  Yes         
##  6 CUST00006  Female Not Senior    No      Yes         0.470  Yes         
##  7 CUST00007  Female Not Senior    Yes     No         -0.0106 Yes         
##  8 CUST00008  Female Not Senior    Yes     Yes        -0.732  Yes         
##  9 CUST00009  Female Not Senior    Yes     Yes         0.615  No          
## 10 CUST00010  Female Not Senior    No      No         -0.107  Yes         
## # i 9,962 more rows
## # i 5 more variables: InternetService <fct>, Contract <fct>,
## #   MonthlyCharges <dbl>, TotalCharges <dbl>, Churn <fct>
\end{verbatim}

\subsubsection{Review}\label{review}

In this chapter, we simply loaded up the data, and cleaned/transformed
it so that it is much better suited for use in machine learning. Some of
the things we did is transformed categorical variables into an R factor
data type, which would make it easier for the machine to use. We also
Z-score normalized our data, and removed outliers (removing data points
with a z-score of \textgreater{} 3).

We also explored the distribution of the Monthly Charges for gender and
churn category, finding minimal differences. We also found that the
monthly charges differed for males and females with regards to tenure.

\subsection{Tuning Predictive Models}\label{tuning-predictive-models}

\subsubsection{Model Complexity}\label{model-complexity}

Now, let's try fitting a decision tree and a logistic regression model
to our data set.

Let's first double check our data:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cust\_churn\_norm\_features }\OtherTok{\textless{}{-}}\NormalTok{ cust\_churn\_norm }\SpecialCharTok{\%\textgreater{}\%}\NormalTok{ dplyr}\SpecialCharTok{::}\FunctionTok{select}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{CustomerID)}

\NormalTok{vars\_to\_check }\OtherTok{\textless{}{-}}\NormalTok{ cust\_churn\_norm\_features }\SpecialCharTok{\%\textgreater{}\%} 
\NormalTok{  dplyr}\SpecialCharTok{::}\FunctionTok{select}\NormalTok{(}\FunctionTok{where}\NormalTok{(is.factor) ) }\SpecialCharTok{\%\textgreater{}\%}
\NormalTok{  dplyr}\SpecialCharTok{::}\FunctionTok{select}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{Churn) }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{names}\NormalTok{()}

\ControlFlowTok{for}\NormalTok{ (var }\ControlFlowTok{in}\NormalTok{ vars\_to\_check) \{}
  
\NormalTok{  formula }\OtherTok{\textless{}{-}} \FunctionTok{as.formula}\NormalTok{(}\FunctionTok{paste}\NormalTok{(}\StringTok{"\textasciitilde{} Churn +"}\NormalTok{, var))}
  
\NormalTok{  tbl }\OtherTok{\textless{}{-}} \FunctionTok{xtabs}\NormalTok{(formula, }\AttributeTok{data =}\NormalTok{ cust\_churn\_norm\_features)}
  
  \FunctionTok{print}\NormalTok{(tbl)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      Gender
## Churn Female Male
##   No    3663 3614
##   Yes   1402 1293
##      SeniorCitizen
## Churn Not Senior Senior Citizen
##   No        6175           1102
##   Yes       2298            397
##      Partner
## Churn   No  Yes
##   No  3615 3662
##   Yes 1368 1327
##      Dependents
## Churn   No  Yes
##   No  5082 2195
##   Yes 1913  782
##      PhoneService
## Churn   No  Yes
##   No   685 6592
##   Yes  277 2418
##      InternetService
## Churn  DSL Fiber optic   No
##   No  2888        2926 1463
##   Yes 1086        1100  509
##      Contract
## Churn Month-to-month One year Two year
##   No            4320     1514     1443
##   Yes           1639      494      562
\end{verbatim}

As we can see, we have data points in all of the intersections of churn
and other factor variables. However, what's worrying is the intersection
of ``yes'' in churn and Senior Citizens. But let's find out later if it
will be a problem.

Let's first create the splits:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)}

\NormalTok{trainIndex }\OtherTok{\textless{}{-}} \FunctionTok{createDataPartition}\NormalTok{(cust\_churn\_norm\_features}\SpecialCharTok{$}\NormalTok{Churn, }\AttributeTok{p =}\NormalTok{ .}\DecValTok{8}\NormalTok{, }
                                  \AttributeTok{list =} \ConstantTok{FALSE}\NormalTok{, }
                                  \AttributeTok{times =} \DecValTok{1}\NormalTok{)}

\NormalTok{churnTrain }\OtherTok{\textless{}{-}}\NormalTok{ cust\_churn\_norm\_features[ trainIndex,]}
\NormalTok{churnTest  }\OtherTok{\textless{}{-}}\NormalTok{ cust\_churn\_norm\_features[}\SpecialCharTok{{-}}\NormalTok{trainIndex,]}
\end{Highlighting}
\end{Shaded}

Let's now create our logistic regression.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{model\_logistic }\OtherTok{\textless{}{-}} \FunctionTok{glm}\NormalTok{(}\AttributeTok{formula =}\NormalTok{ Churn }\SpecialCharTok{\textasciitilde{}}\NormalTok{ ., }\AttributeTok{family =} \StringTok{"binomial"}\NormalTok{, }\AttributeTok{data=}\NormalTok{cust\_churn\_norm\_features)}

\FunctionTok{summary}\NormalTok{(model\_logistic)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## glm(formula = Churn ~ ., family = "binomial", data = cust_churn_norm_features)
## 
## Coefficients:
##                              Estimate Std. Error z value Pr(>|z|)    
## (Intercept)                 -0.783674   0.086842  -9.024  < 2e-16 ***
## GenderMale                  -0.069111   0.045218  -1.528  0.12642    
## SeniorCitizenSenior Citizen -0.032045   0.063528  -0.504  0.61396    
## PartnerYes                  -0.042498   0.045173  -0.941  0.34682    
## DependentsYes               -0.059519   0.049621  -1.199  0.23035    
## Tenure                       0.069629   0.058866   1.183  0.23687    
## PhoneServiceYes             -0.102348   0.075195  -1.361  0.17348    
## InternetServiceFiber optic   0.001558   0.050266   0.031  0.97527    
## InternetServiceNo           -0.081882   0.062681  -1.306  0.19144    
## ContractOne year            -0.155395   0.059461  -2.613  0.00897 ** 
## ContractTwo year             0.025314   0.057619   0.439  0.66042    
## MonthlyCharges               0.026633   0.045000   0.592  0.55395    
## TotalCharges                -0.079574   0.070277  -1.132  0.25751    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 11638  on 9971  degrees of freedom
## Residual deviance: 11619  on 9959  degrees of freedom
## AIC: 11645
## 
## Number of Fisher Scoring iterations: 4
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ll.null }\OtherTok{\textless{}{-}}\NormalTok{ model\_logistic}\SpecialCharTok{$}\NormalTok{null.deviance}\SpecialCharTok{/{-}}\DecValTok{2}
\NormalTok{ll.proposed }\OtherTok{\textless{}{-}}\NormalTok{ model\_logistic}\SpecialCharTok{$}\NormalTok{deviance}\SpecialCharTok{/{-}}\DecValTok{2}

\FunctionTok{cat}\NormalTok{(}\StringTok{"}\SpecialCharTok{\textbackslash{}n\textbackslash{}n}\StringTok{The Psuedo R\^{}2 is:"}\NormalTok{, (ll.null}\SpecialCharTok{{-}}\NormalTok{ll.proposed)}\SpecialCharTok{/}\NormalTok{ll.null)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## 
## The Psuedo R^2 is: 0.001593432
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{And the p{-}value is: "}\NormalTok{, }\DecValTok{1}\SpecialCharTok{{-}}\FunctionTok{pchisq}\NormalTok{(}\DecValTok{2}\SpecialCharTok{*}\NormalTok{(ll.proposed}\SpecialCharTok{{-}}\NormalTok{ll.null), }\AttributeTok{df=}\NormalTok{(}\FunctionTok{length}\NormalTok{(model\_logistic}\SpecialCharTok{$}\NormalTok{coefficients)}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## And the p-value is:  0.1001508
\end{verbatim}

Given by the p-value (R\^{}2 = 0.0016, p-val = 0.1) , we can say that
the regression does not properly predict Churn. However, we can see that
the contract length does have a significant effect in the regression (Z
= -1.989, p-value = 0.467), specifically the one year contracts.

Let's try only using the contracts.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{model\_logistic\_2 }\OtherTok{\textless{}{-}} \FunctionTok{glm}\NormalTok{(}\AttributeTok{formula =}\NormalTok{ Churn }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Contract, }\AttributeTok{family =} \StringTok{"binomial"}\NormalTok{, }\AttributeTok{data=}\NormalTok{cust\_churn\_norm\_features)}

\FunctionTok{summary}\NormalTok{(model\_logistic\_2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## glm(formula = Churn ~ Contract, family = "binomial", data = cust_churn_norm_features)
## 
## Coefficients:
##                  Estimate Std. Error z value Pr(>|z|)    
## (Intercept)      -0.96917    0.02901 -33.408   <2e-16 ***
## ContractOne year -0.15081    0.05938  -2.540   0.0111 *  
## ContractTwo year  0.02619    0.05757   0.455   0.6491    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 11638  on 9971  degrees of freedom
## Residual deviance: 11630  on 9969  degrees of freedom
## AIC: 11636
## 
## Number of Fisher Scoring iterations: 4
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ll.null }\OtherTok{\textless{}{-}}\NormalTok{ model\_logistic\_2}\SpecialCharTok{$}\NormalTok{null.deviance}\SpecialCharTok{/{-}}\DecValTok{2}
\NormalTok{ll.proposed }\OtherTok{\textless{}{-}}\NormalTok{ model\_logistic\_2}\SpecialCharTok{$}\NormalTok{deviance}\SpecialCharTok{/{-}}\DecValTok{2}

\FunctionTok{cat}\NormalTok{(}\StringTok{"}\SpecialCharTok{\textbackslash{}n\textbackslash{}n}\StringTok{The Psuedo R\^{}2 is:"}\NormalTok{, (ll.null}\SpecialCharTok{{-}}\NormalTok{ll.proposed)}\SpecialCharTok{/}\NormalTok{ll.null)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## 
## The Psuedo R^2 is: 0.0006711029
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{And the p{-}value is: "}\NormalTok{, }\DecValTok{1}\SpecialCharTok{{-}}\FunctionTok{pchisq}\NormalTok{(}\DecValTok{2}\SpecialCharTok{*}\NormalTok{(ll.proposed}\SpecialCharTok{{-}}\NormalTok{ll.null), }\AttributeTok{df=}\NormalTok{(}\FunctionTok{length}\NormalTok{(model\_logistic\_2}\SpecialCharTok{$}\NormalTok{coefficients)}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## And the p-value is:  0.02014065
\end{verbatim}

We can see that the model did better than the last, getting a better
result (R\^{}2 = 0.00066, p-val = 0.084).

let's now get the AUC of both:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{predicted\_probs }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(model\_logistic, }\AttributeTok{type =} \StringTok{"response"}\NormalTok{)}
\NormalTok{roc\_curve }\OtherTok{\textless{}{-}} \FunctionTok{roc}\NormalTok{(cust\_churn\_norm\_features}\SpecialCharTok{$}\NormalTok{Churn, predicted\_probs)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Setting levels: control = No, case = Yes
\end{verbatim}

\begin{verbatim}
## Setting direction: controls < cases
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{auc\_value }\OtherTok{\textless{}{-}}\NormalTok{ pROC}\SpecialCharTok{::}\FunctionTok{auc}\NormalTok{(roc\_curve)}
\FunctionTok{cat}\NormalTok{(}\StringTok{"AUC of first model:"}\NormalTok{, auc\_value, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## AUC of first model: 0.5267711
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{predicted\_probs }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(model\_logistic\_2, }\AttributeTok{type =} \StringTok{"response"}\NormalTok{)}
\NormalTok{roc\_curve }\OtherTok{\textless{}{-}} \FunctionTok{roc}\NormalTok{(cust\_churn\_norm\_features}\SpecialCharTok{$}\NormalTok{Churn, predicted\_probs)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Setting levels: control = No, case = Yes
## Setting direction: controls < cases
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{auc\_value }\OtherTok{\textless{}{-}}\NormalTok{ pROC}\SpecialCharTok{::}\FunctionTok{auc}\NormalTok{(roc\_curve)}
\FunctionTok{cat}\NormalTok{(}\StringTok{"AUC of second model:"}\NormalTok{, auc\_value, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## AUC of second model: 0.5139753
\end{verbatim}

Despite the first model getting a lower p-value than the second, we can
see that the first model, albeit slightly, performs better than the
second. Overall, both models are bad, and are no better than making our
own guesses.

Now, let's try using decision trees.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{churn.tree }\OtherTok{\textless{}{-}} \FunctionTok{train}\NormalTok{(}
\NormalTok{  Churn }\SpecialCharTok{\textasciitilde{}}\NormalTok{ .,}
  \AttributeTok{data =}\NormalTok{ churnTrain,}
  \AttributeTok{method=}\StringTok{"rpart"}\NormalTok{,}
  \AttributeTok{trControl =} \FunctionTok{trainControl}\NormalTok{(}\AttributeTok{method =} \StringTok{"cv"}\NormalTok{, }\AttributeTok{number=}\DecValTok{10}\NormalTok{, }\AttributeTok{classProbs =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{summaryFunction =}\NormalTok{ twoClassSummary),}
  \AttributeTok{tuneGrid =} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{cp =} \FunctionTok{seq}\NormalTok{(}\DecValTok{0}\NormalTok{, }\FloatTok{0.01}\NormalTok{, }\AttributeTok{by =} \FloatTok{0.001}\NormalTok{)),}
  \AttributeTok{weights =} \FunctionTok{ifelse}\NormalTok{(churnTrain}\SpecialCharTok{$}\NormalTok{Churn }\SpecialCharTok{==} \StringTok{"Yes"}\NormalTok{,}\DecValTok{12}\NormalTok{, }\DecValTok{1}\NormalTok{),}
  \AttributeTok{metric =} \StringTok{"ROC"}
  
\NormalTok{  )}

\NormalTok{churn.tree}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## CART 
## 
## 7978 samples
##   10 predictor
##    2 classes: 'No', 'Yes' 
## 
## No pre-processing
## Resampling: Cross-Validated (10 fold) 
## Summary of sample sizes: 7181, 7181, 7179, 7180, 7179, 7181, ... 
## Resampling results across tuning parameters:
## 
##   cp     ROC        Sens          Spec     
##   0.000  0.4962488  0.2636684880  0.7337554
##   0.001  0.4861030  0.0353863474  0.9624268
##   0.002  0.5018550  0.0046379964  0.9990719
##   0.003  0.4997937  0.0005154639  0.9990719
##   0.004  0.5000252  0.0005154639  0.9995349
##   0.005  0.5000000  0.0000000000  1.0000000
##   0.006  0.5000000  0.0000000000  1.0000000
##   0.007  0.5000000  0.0000000000  1.0000000
##   0.008  0.5000000  0.0000000000  1.0000000
##   0.009  0.5000000  0.0000000000  1.0000000
##   0.010  0.5000000  0.0000000000  1.0000000
## 
## ROC was used to select the optimal model using the largest value.
## The final value used for the model was cp = 0.002.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{predicted\_probs }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(churn.tree, }\AttributeTok{newdata =}\NormalTok{ churnTest, }\AttributeTok{type =} \StringTok{"prob"}\NormalTok{)}\SpecialCharTok{$}\NormalTok{Yes}

\CommentTok{\# Calculate the ROC curve}
\NormalTok{roc\_curve }\OtherTok{\textless{}{-}} \FunctionTok{roc}\NormalTok{(churnTest}\SpecialCharTok{$}\NormalTok{Churn, predicted\_probs)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Setting levels: control = No, case = Yes
\end{verbatim}

\begin{verbatim}
## Setting direction: controls < cases
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Compute the AUC}
\NormalTok{auc\_value }\OtherTok{\textless{}{-}}\NormalTok{ pROC}\SpecialCharTok{::}\FunctionTok{auc}\NormalTok{(roc\_curve)}
\FunctionTok{print}\NormalTok{(}\FunctionTok{paste}\NormalTok{(}\StringTok{"ROC AUC:"}\NormalTok{, auc\_value))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "ROC AUC: 0.502061855670103"
\end{verbatim}

Setting the weight of Churn = ``Yes'' to 12, yields the best results
(ROC AUC = 0.505).

\subsubsection{Bias-Variance Trade Off}\label{bias-variance-trade-off}

The Bias-Variance trade-off is more apparent with our decision tree, in
which we are adusting the cp, which is related to how many splits our
decision tree makes. The lower the cp, the more splits it makes, and the
more complex the model is.

By increasing the complexity, or decreasing bias, we tend to capture the
trends better, but a higher complexity leads to over fitting, making the
model unable to properly function for new data points. But if we did not
highten the complexity, in our case, we would underfit, i.e.~we won't be
able to make accurate predictions because the model does not see the
trends.

In relation to our logistic regression, our complexity is related to the
number of predictors used. When we decreased the complexity, we
increased our bias, leading to our model to underfit worse than the
model with the complete predictors.

\subsubsection{Cross-Validation}\label{cross-validation}

Let's use caret to create our cross validation model, and accuracy,
precision, recall, and F1-score:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{train\_control }\OtherTok{\textless{}{-}} \FunctionTok{trainControl}\NormalTok{(}
  \AttributeTok{method =} \StringTok{"repeatedcv"}\NormalTok{,}
  \AttributeTok{repeats =} \DecValTok{3}\NormalTok{,}
  \AttributeTok{number =} \DecValTok{10}\NormalTok{,  }
  \AttributeTok{classProbs =} \ConstantTok{TRUE}\NormalTok{,}
  \AttributeTok{summaryFunction =} \ControlFlowTok{function}\NormalTok{(data, }\AttributeTok{lev =} \ConstantTok{NULL}\NormalTok{, }\AttributeTok{model =} \ConstantTok{NULL}\NormalTok{) \{}
\NormalTok{    default }\OtherTok{\textless{}{-}} \FunctionTok{defaultSummary}\NormalTok{(data, lev, model)}
\NormalTok{    pr }\OtherTok{\textless{}{-}} \FunctionTok{prSummary}\NormalTok{(data, lev, model)}
    \FunctionTok{c}\NormalTok{(default, pr)}
\NormalTok{  \},}
  \AttributeTok{savePredictions =} \ConstantTok{TRUE}
\NormalTok{)}

\NormalTok{model\_cv }\OtherTok{\textless{}{-}} \FunctionTok{train}\NormalTok{(}
\NormalTok{  Churn }\SpecialCharTok{\textasciitilde{}}\NormalTok{ .,}
  \AttributeTok{data =}\NormalTok{ churnTrain,}
  \AttributeTok{method =} \StringTok{"rpart"}\NormalTok{, }
  \AttributeTok{trControl =}\NormalTok{ train\_control,}
  \CommentTok{\#weights = ifelse(churnTrain$Churn == "Yes",12, 1),}
  \AttributeTok{metric =} \StringTok{"Accuracy"}
\NormalTok{)}

\CommentTok{\# Print the model summary}
\FunctionTok{print}\NormalTok{(model\_cv)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## CART 
## 
## 7978 samples
##   10 predictor
##    2 classes: 'No', 'Yes' 
## 
## No pre-processing
## Resampling: Cross-Validated (10 fold, repeated 3 times) 
## Summary of sample sizes: 7180, 7180, 7179, 7181, 7181, 7181, ... 
## Resampling results across tuning parameters:
## 
##   cp            Accuracy   Kappa         AUC        Precision  Recall   
##   0.0006029685  0.7121250  -0.005970814  0.6256356  0.7288211  0.9642768
##   0.0006957328  0.7229446  -0.003192634  0.3364527  0.7292829  0.9865438
##   0.0007168157  0.7236137  -0.002601137  0.3131209  0.7293700  0.9877466
##   F        
##   0.8299766
##   0.8385476
##   0.8390416
## 
## Accuracy was used to select the optimal model using the largest value.
## The final value used for the model was cp = 0.0007168157.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# View the cross{-}validation results}
\NormalTok{cv\_results }\OtherTok{\textless{}{-}}\NormalTok{ model\_cv}\SpecialCharTok{$}\NormalTok{results}
\FunctionTok{print}\NormalTok{(cv\_results }\SpecialCharTok{\%\textgreater{}\%}\NormalTok{ dplyr}\SpecialCharTok{::}\FunctionTok{select}\NormalTok{(cp, Accuracy, Precision, Recall, F))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##             cp  Accuracy Precision    Recall         F
## 1 0.0006029685 0.7121250 0.7288211 0.9642768 0.8299766
## 2 0.0006957328 0.7229446 0.7292829 0.9865438 0.8385476
## 3 0.0007168157 0.7236137 0.7293700 0.9877466 0.8390416
\end{verbatim}

the cp value of 0.0006029685 had the lowest accuracy (0.7148369), Recall
(0.9652995), and F-stat (0.8314882), but it has the highest precision
(0.7305843). It is also the most complex iteration of the model.

The model that the caret library deemed optimal is the cp value of
0.0007168157, giving the highest accuracy (0.7214809), recall
(0.9807560), and F statistic (0.8369769), with the least complexity.

cp value of 0.0006957328 gave the same results, but is slightly more
complex than the optimal.

\subsubsection{Classification}\label{classification}

Let's try using a Random Forest Classifier model to predict customer
churn.

\subsection{Regression-Based Methods}\label{regression-based-methods}

We have previously tried classification methods. Now, let's try
regression methods.

\subsubsection{Logistic Regression}\label{logistic-regression}

Let's fit a logistic regression model using Churn as the dependent
variable and Tenure, MonthlyCharges, and TotalCharges as independent
variables. Then, let's Interpret the coefficients and assess model
significance using p-values.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{model\_logistic\_fin }\OtherTok{\textless{}{-}} \FunctionTok{glm}\NormalTok{(}\AttributeTok{formula =}\NormalTok{ Churn }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Tenure }\SpecialCharTok{+}\NormalTok{ MonthlyCharges }\SpecialCharTok{+}\NormalTok{ TotalCharges, }\AttributeTok{family =} \StringTok{"binomial"}\NormalTok{, }\AttributeTok{data=}\NormalTok{churnTrain)}

\FunctionTok{summary}\NormalTok{(model\_logistic\_fin)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## glm(formula = Churn ~ Tenure + MonthlyCharges + TotalCharges, 
##     family = "binomial", data = churnTrain)
## 
## Coefficients:
##                Estimate Std. Error z value Pr(>|z|)    
## (Intercept)    -0.99388    0.02522 -39.408   <2e-16 ***
## Tenure          0.05692    0.06611   0.861    0.389    
## MonthlyCharges  0.02075    0.05085   0.408    0.683    
## TotalCharges   -0.05710    0.07886  -0.724    0.469    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 9310.3  on 7977  degrees of freedom
## Residual deviance: 9309.3  on 7974  degrees of freedom
## AIC: 9317.3
## 
## Number of Fisher Scoring iterations: 4
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ll.null }\OtherTok{\textless{}{-}}\NormalTok{ model\_logistic\_fin}\SpecialCharTok{$}\NormalTok{null.deviance}\SpecialCharTok{/{-}}\DecValTok{2}
\NormalTok{ll.proposed }\OtherTok{\textless{}{-}}\NormalTok{ model\_logistic\_fin}\SpecialCharTok{$}\NormalTok{deviance}\SpecialCharTok{/{-}}\DecValTok{2}

\FunctionTok{cat}\NormalTok{(}\StringTok{"}\SpecialCharTok{\textbackslash{}n\textbackslash{}n}\StringTok{The Psuedo R\^{}2 is:"}\NormalTok{, (ll.null}\SpecialCharTok{{-}}\NormalTok{ll.proposed)}\SpecialCharTok{/}\NormalTok{ll.null)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## 
## The Psuedo R^2 is: 0.0001060756
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{And the p{-}value is: "}\NormalTok{, }\DecValTok{1}\SpecialCharTok{{-}}\FunctionTok{pchisq}\NormalTok{(}\DecValTok{2}\SpecialCharTok{*}\NormalTok{(ll.proposed}\SpecialCharTok{{-}}\NormalTok{ll.null), }\AttributeTok{df=}\NormalTok{(}\FunctionTok{length}\NormalTok{(model\_logistic\_fin}\SpecialCharTok{$}\NormalTok{coefficients)}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## And the p-value is:  0.8042524
\end{verbatim}

It seems like no coefficient correlated significantly to Churn. The
closest would be tenure (Z = 0.861, p-val = 0.389), followed by Total
Charges (z = -0.724, p-val = 0.469), and finally, the Monthly Charges (z
= 0.408, p-val = 0.683). All p-value is insignificant.

The overall p-value of the model is 0.804, with a Psuedo \(R^2\) of
0.0001

This all shows that the model is not able to predict customer churn, as
all variables do not correlate with it.

\subsubsection{Regression in High
Dimensions}\label{regression-in-high-dimensions}

Having a high-dimensional model can be pretty problematic.

First, they can be pretty hard on the machine, needing long training
times.

Second, they can cause overfitting, leading to the model not being able
to see the pattern of the data. This leads to errors in predicting the
result when a new data point comes.,

third, is that most of the time, predictors correlate with each other,
which can ruin the training of the model.

One way to combat this is to use Principal Component Analysis (PCA) on
numerical features to be use variables that correlate together as one
component, instead of using all of them.

Let's try creating a PCA of Tenure, MonthlyCharges, and TotalCharges.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{numeric\_scaled\_data }\OtherTok{\textless{}{-}}\NormalTok{ cust\_churn\_norm\_features }\SpecialCharTok{\%\textgreater{}\%}\NormalTok{ dplyr}\SpecialCharTok{::}\FunctionTok{select}\NormalTok{(}\FunctionTok{where}\NormalTok{(is.numeric))}

\NormalTok{pca\_result }\OtherTok{\textless{}{-}} \FunctionTok{prcomp}\NormalTok{(numeric\_scaled\_data, }\AttributeTok{center =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{scale. =} \ConstantTok{TRUE}\NormalTok{)}

\FunctionTok{print}\NormalTok{(pca\_result)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Standard deviations (1, .., p=3):
## [1] 1.383578 1.015932 0.231504
## 
## Rotation (n x k) = (3 x 3):
##                       PC1         PC2        PC3
## Tenure         -0.5811163  0.57012040 -0.5807466
## MonthlyCharges -0.3921231 -0.82146001 -0.4140566
## TotalCharges   -0.7131222 -0.01289089  0.7009212
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"}\SpecialCharTok{\textbackslash{}n\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(pca\_result)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Importance of components:
##                           PC1    PC2     PC3
## Standard deviation     1.3836 1.0159 0.23150
## Proportion of Variance 0.6381 0.3440 0.01786
## Cumulative Proportion  0.6381 0.9821 1.00000
\end{verbatim}

We can see that the first component is negatively correlated to both
Tenure (R=-0.5811163 ) and Total Charges (R=-0.7131222), and
significantly so. We can then say that, when tenure decreases, the total
charge also decreases. This makes sense, because customers with higher
tenure pay more in the long run.

The second component is significantly correlated with Tenure
(R=0.57012040), while is negatively correlated with Monthly Charges
(R=-0.82146001). This tells us that when the monthly charges increase,
the tenure increases, or vice versa.

The last componenent is then the opposite of the first component, where
it says that it is negatively correlated to Tenure (R=-0.5807466), but
is positively correlated to total charges (R=0.7009212)

\subsubsection{Ridge Regression}\label{ridge-regression}

Implement Ridge Regression using Churn as the target variable and
Tenure, MonthlyCharges, TotalCharges, and additional customer
demographic features as predictors.

Identify the optimal lambda using cross-validation.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{predictors }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"Tenure"}\NormalTok{, }\StringTok{"MonthlyCharges"}\NormalTok{, }\StringTok{"TotalCharges"}\NormalTok{)}

\NormalTok{encoded\_contract }\OtherTok{\textless{}{-}} \FunctionTok{model.matrix}\NormalTok{(}\SpecialCharTok{\textasciitilde{}}\NormalTok{ Contract }\SpecialCharTok{{-}} \DecValTok{1}\NormalTok{, }\AttributeTok{data =}\NormalTok{ churnTrain)}
\NormalTok{encoded\_contract }\OtherTok{\textless{}{-}} \FunctionTok{as.data.frame}\NormalTok{(encoded\_contract)}
\NormalTok{num\_preds }\OtherTok{\textless{}{-}}\NormalTok{ churnTrain  }\SpecialCharTok{\%\textgreater{}\%}\NormalTok{ dplyr}\SpecialCharTok{::}\FunctionTok{select}\NormalTok{(}\FunctionTok{all\_of}\NormalTok{(predictors)) }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{as.data.frame}\NormalTok{()}
\NormalTok{preds }\OtherTok{\textless{}{-}} \FunctionTok{cbind}\NormalTok{(num\_preds, encoded\_contract)}

\NormalTok{enc\_cont\_test }\OtherTok{\textless{}{-}} \FunctionTok{model.matrix}\NormalTok{(}\SpecialCharTok{\textasciitilde{}}\NormalTok{ Contract }\SpecialCharTok{{-}} \DecValTok{1}\NormalTok{, }\AttributeTok{data =}\NormalTok{ churnTest)}
\NormalTok{enc\_cont\_test }\OtherTok{\textless{}{-}} \FunctionTok{as.data.frame}\NormalTok{(enc\_cont\_test)}
\NormalTok{preds\_num\_test }\OtherTok{\textless{}{-}}\NormalTok{ churnTest  }\SpecialCharTok{\%\textgreater{}\%}\NormalTok{ dplyr}\SpecialCharTok{::}\FunctionTok{select}\NormalTok{(}\FunctionTok{all\_of}\NormalTok{(predictors)) }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{as.data.frame}\NormalTok{()}
\NormalTok{preds\_test }\OtherTok{\textless{}{-}} \FunctionTok{cbind}\NormalTok{(preds\_num\_test, enc\_cont\_test)}


\NormalTok{y }\OtherTok{\textless{}{-}}\NormalTok{ churnTrain  }\SpecialCharTok{\%\textgreater{}\%}\NormalTok{ dplyr}\SpecialCharTok{::}\FunctionTok{select}\NormalTok{(Churn)}

\CommentTok{\# Set up cross{-}validation}
\NormalTok{ctrl }\OtherTok{\textless{}{-}} \FunctionTok{trainControl}\NormalTok{(}
  \AttributeTok{method =} \StringTok{"cv"}\NormalTok{,}
  \AttributeTok{number =} \DecValTok{10}\NormalTok{,}
\NormalTok{)}

\NormalTok{weight }\OtherTok{=} \FloatTok{2.70037105751}
\NormalTok{ridge\_model }\OtherTok{\textless{}{-}} \FunctionTok{train}\NormalTok{(}
  \AttributeTok{x =}\NormalTok{ preds,}
  \AttributeTok{y =}\NormalTok{ y}\SpecialCharTok{$}\NormalTok{Churn,}
  \AttributeTok{method =} \StringTok{"glmnet"}\NormalTok{,}
  \AttributeTok{trControl =}\NormalTok{ ctrl,}
  \AttributeTok{tuneGrid =} \FunctionTok{expand.grid}\NormalTok{(}\AttributeTok{alpha =} \DecValTok{0}\NormalTok{, }\AttributeTok{lambda =} \FunctionTok{seq}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{50}\NormalTok{, }\AttributeTok{length =} \DecValTok{51}\NormalTok{)),}
  \AttributeTok{weights =} \FunctionTok{ifelse}\NormalTok{(churnTrain}\SpecialCharTok{$}\NormalTok{Churn }\SpecialCharTok{==} \StringTok{"Yes"}\NormalTok{,weight, }\DecValTok{1}\NormalTok{),}
\NormalTok{)}

\FunctionTok{cat}\NormalTok{(}\StringTok{"The optimal lambda is:"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## The optimal lambda is:
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(ridge\_model}\SpecialCharTok{$}\NormalTok{bestTune}\SpecialCharTok{$}\NormalTok{lambda)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Make predictions and evaluate the model}
\NormalTok{predictions }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(ridge\_model, }\AttributeTok{newdata =}\NormalTok{ preds\_test)}
\NormalTok{predictions }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(predictions, }\AttributeTok{levels =} \FunctionTok{levels}\NormalTok{(y}\SpecialCharTok{$}\NormalTok{Churn))}
\FunctionTok{confusionMatrix}\NormalTok{(predictions, churnTest}\SpecialCharTok{$}\NormalTok{Churn)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Confusion Matrix and Statistics
## 
##           Reference
## Prediction   No  Yes
##        No  1455  539
##        Yes    0    0
##                                           
##                Accuracy : 0.7297          
##                  95% CI : (0.7096, 0.7491)
##     No Information Rate : 0.7297          
##     P-Value [Acc > NIR] : 0.5116          
##                                           
##                   Kappa : 0               
##                                           
##  Mcnemar's Test P-Value : <2e-16          
##                                           
##             Sensitivity : 1.0000          
##             Specificity : 0.0000          
##          Pos Pred Value : 0.7297          
##          Neg Pred Value :    NaN          
##              Prevalence : 0.7297          
##          Detection Rate : 0.7297          
##    Detection Prevalence : 1.0000          
##       Balanced Accuracy : 0.5000          
##                                           
##        'Positive' Class : No              
## 
\end{verbatim}

The in this particular ridge regression model, the most optimal lambda
value is 50. I wager that if we increase the lambda value, it will take
the highest possible value.

Looking at the confusion matrix, the model only gives out a prediction
of ``No'', Changing the weight of ``Yes'' in training seemes to be able
to improve things, but after multiple iterations, the model only gives
out ``Yes'' (true positives and false positives), or ``No'' (True
Negatives or False Negatives) with each change. A better interpolation
approach would be required into making this into a working model.

However, due to the prevalence of ``No'', it is correct 0.7297
accounting to ``No'' being some 73\% of the dataset. The p-value given
by the model is 0.5116.

\subsubsection{Lasso Regression}\label{lasso-regression}

Now, let's try the Lasso Regression

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lasso\_model }\OtherTok{\textless{}{-}} \FunctionTok{train}\NormalTok{(}
  \AttributeTok{x =}\NormalTok{ preds,}
  \AttributeTok{y =}\NormalTok{ y}\SpecialCharTok{$}\NormalTok{Churn,}
  \AttributeTok{method =} \StringTok{"glmnet"}\NormalTok{,}
  \AttributeTok{trControl =}\NormalTok{ ctrl,}
  \AttributeTok{tuneGrid =} \FunctionTok{expand.grid}\NormalTok{(}\AttributeTok{alpha =} \DecValTok{0}\NormalTok{, }\AttributeTok{lambda =} \FunctionTok{seq}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{50}\NormalTok{, }\AttributeTok{length =} \DecValTok{51}\NormalTok{)),}
  \AttributeTok{weights =} \FunctionTok{ifelse}\NormalTok{(churnTrain}\SpecialCharTok{$}\NormalTok{Churn }\SpecialCharTok{==} \StringTok{"Yes"}\NormalTok{,weight, }\DecValTok{1}\NormalTok{),}
\NormalTok{)}

\FunctionTok{cat}\NormalTok{(}\StringTok{"The optimal lambda is:"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## The optimal lambda is:
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(lasso\_model}\SpecialCharTok{$}\NormalTok{bestTune}\SpecialCharTok{$}\NormalTok{lambda)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 50
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Make predictions and evaluate the model}
\NormalTok{predictions\_lasso }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(lasso\_model, }\AttributeTok{newdata =}\NormalTok{ preds\_test)}
\NormalTok{predictions\_lasso }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(predictions\_lasso, }\AttributeTok{levels =} \FunctionTok{levels}\NormalTok{(y}\SpecialCharTok{$}\NormalTok{Churn))}
\FunctionTok{confusionMatrix}\NormalTok{(predictions\_lasso, churnTest}\SpecialCharTok{$}\NormalTok{Churn)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Confusion Matrix and Statistics
## 
##           Reference
## Prediction   No  Yes
##        No  1455  539
##        Yes    0    0
##                                           
##                Accuracy : 0.7297          
##                  95% CI : (0.7096, 0.7491)
##     No Information Rate : 0.7297          
##     P-Value [Acc > NIR] : 0.5116          
##                                           
##                   Kappa : 0               
##                                           
##  Mcnemar's Test P-Value : <2e-16          
##                                           
##             Sensitivity : 1.0000          
##             Specificity : 0.0000          
##          Pos Pred Value : 0.7297          
##          Neg Pred Value :    NaN          
##              Prevalence : 0.7297          
##          Detection Rate : 0.7297          
##    Detection Prevalence : 1.0000          
##       Balanced Accuracy : 0.5000          
##                                           
##        'Positive' Class : No              
## 
\end{verbatim}

The lasso regression provides the same exact results as the ridge
regression.

\end{document}
